### ISSUE TITLE
close= crashes when open= has failed

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.release.test#1]
Using morphy_nui_v0b1Winx64.exe, downloaded 2020-01-27.

File to replicate:
- [hyo.nex.txt](https://github.com/mbrazeau/morphy.release.test/files/4116947/hyo.nex.txt) (Note I had to add a .txt extension to be allowed to upload to GH)

Commands to replicate:
```
cd = path/to/dir

open = hyo.nex

close = hyo.nex
```

`open` fails with `Error: invalid vector subscript` (#2), then `close = ` causes the program to crash and terminate.

**Comment by mbrazeau** [comment]
There seems to be a problem with the NCL NexusReader class reading data files with some unexpected tokens (or missing tokens, like the symbols list in the data format command). I will need to do some work on the file reader class in the interface to fix this.

**Comment by mbrazeau** [comment]
This is fixed in the source code now. My windows machine is undergoing maintenance and backing up right now, so uploading new windows binaries will have to wait, unfortunately. I'll keep this open until I get the chance to replace the binaries. You can try re-building from source.

**Comment by mbrazeau** [comment]
issue should be fixed and windows builds updated
