### ISSUE TITLE
Error: invalid vector subscript when STATELABELS present

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.release.test#2]
morphy_nui_v0b1Winx64.exe

Command: `open = hyo.nex`

Returns `Error: invalid vector subscript` when StateLabels block is present:
[hyo.nex.statelabels.txt](https://github.com/mbrazeau/morphy.release.test/files/4116966/hyo.nex.statelabels.txt)

But not when StateLabels block is deleted:
[hyo.nex.nostatelabels.txt](https://github.com/mbrazeau/morphy.release.test/files/4116967/hyo.nex.nostatelabels.txt)

Files need renaming to `hyo.nex` to reproduce.

**Comment by mbrazeau** [comment]
This could be a problem with the NCL rather than morphy itself. I recommend just leaving those off. Will investigate.

**Comment by mbrazeau** [comment]
Same fix as Issue #1 . The program still won't read those files and the statelabels block will have to be removed or commented out. But it should no longer cause crashes. I can eventually update the reader to avoid doing this.

**Comment by mbrazeau** [comment]
windows builds are updated now
