### ISSUE TITLE
Using open= with full path

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.release.test#4]
Using morphy_nui_v0b1Winx64.exe 

```
open = c:/research/r/hyoliths/morphy/hyo.nex
``` 
fails, seemingly because `./` is prepended to `c:/`
(Message: `Unable to read ./c:/research/r/hyoliths/morphy/hyo.nex`)

```
cd = c:/research/r/hyoliths/
open = morphy/hyo.nex
``` 
succeeds.

**Comment by mbrazeau** [comment]
This looks like one for @cdesjardins

**Comment by mbrazeau** [comment]
I've actually managed to fix this but not tested on windwos. 

@cdesjardins: the problem appears to have arisen from a failure to check if the input was a path; the current working directory path was then appended to the start of the path name without any check. I've put a conditional check on this, but you might want to see if this is the really the best way to deal with it.
