### ISSUE TITLE
Ratchet unable to iterate search after first iteration

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.release.test#5]
Using morphy_nui_v0b1Winx64.exe and [hyo.nex](https://github.com/mbrazeau/morphy.release.test/files/4117015/hyo.nex.txt)

```
open = hyo.nex
branchswap = spr
nreps = 2
ratchet = yes
heur
```
 
in about 0.5 seconds finds a much better score than plain heuristic!  But gets stuck after the first iteration. (The 8 seconds reported seems like an overestimate here.)

Output:
```
Running: heuristic
Dataset has 225 characters
         -1 characters are parsimony uninformative
         59 characters are treated as type "inapplicable"
Replicate: 1
Initiating ratchet search
        Ratchet iteration 50. Best tree: 630 steps
        Replicate completed.
        Shortest tree found: 630 steps
        Number of trees saved: 1



Heuristic search completed in 8 seconds:
        1754117 rearrangements tried.
        Shortest tree found: 630.000 steps
        24 trees saved
Unable to initiate search.
```

Setting `nreps = 10` and commencing another `heur` runs for a couple of seconds, then returns a similar message 

```
Running: heuristic
Dataset has 225 characters
         -1 characters are parsimony uninformative
         59 characters are treated as type "inapplicable"
Replicate: 1
Initiating ratchet search
        Ratchet iteration 50. Best tree: 628 steps
        Replicate completed.
        Shortest tree found: 629 steps
        Number of trees saved: 0



Heuristic search completed in 7 seconds:
        1599896 rearrangements tried.
        Shortest tree found: 628.000 steps
        5 trees saved
Unable to initiate search.
```

Is this just a case of replacing the message "Unable to initiate search." with "Search complete"?

NB 628 steps matches the TreeSearch score, and what looks like some of the TreeSearch topologies, after a sizeable fraction of an hour.  Fantastic!

For completeness I then tried `nrep = 100`; `heur`,  and see
```
Running: heuristic
Dataset has 225 characters
         -1 characters are parsimony uninformative
         59 characters are treated as type "inapplicable"
Replicate: 1
Initiating ratchet search
        Ratchet iteration 50. Best tree: 632 steps
        Replicate completed.
        Shortest tree found: 632 steps
        Number of trees saved: 0



Heuristic search completed in 5 seconds:
        1457885 rearrangements tried.
        Shortest tree found: 632.000 steps
        4 trees saved
Unable to initiate search.
```

Odd that the shortest tree is now longer!  Also that search did not begin from the previously saved trees?

**Comment by mbrazeau** [comment]
It says "unable to initiate search", not iterate search. This is an output that exists in the (current) Windows build. I'll update it today with the new interface. This was because the mpl returns errors by default and I hadn't yet checked these. These have been fixed now. 

As for why it's now longer, it is because the new search just wiped the buffer clear. I haven't yet programmed a check/warning against. 

Are you finding that the search nreps just isn't updating? It looks like you're only getting a single rep.

**Comment by mbrazeau** [comment]
Ah! I see the problem. You're not setting `addseq=random`. Consequently, it's just performing a ratchet on a single addition sequence using the input order of the taxa.

**Comment by ms609** [comment]
Ah! That all makes sense.  Wonder whether it's worth setting this as a user notice when nreps > 1 & addseq = asis?
